spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

mybatis:
  #\u52A0\u8F7Dmapper\u6587\u4EF6
  mapper-locations: classpath:mapper/*.xml
  #\u8BBE\u7F6E\u5B9E\u4F53\u7C7B\u522B\u540D
  #type-aliases-package: demo.springboot.mybatis6.domain
  #\u52A0\u8F7Dmybatis\u5168\u5C40\u914D\u7F6E\u6587\u4EF6
  #config-location: classpath:mybatis/SqlMapConfig.xml

logging:
  level:
    root: error