spring:
  redis:
    #\u5730\u5740
    host: localhost
    #\u7AEF\u53E3
    port: 6379
    #\u7D22\u5F15\u5E93
    database: 1
    #\u5BC6\u7801
    password: 
    #\u8D85\u65F6\u65F6\u95F4
    timeout: 5000ms

logging:
  level:
    root: error