spring:
  redis:
    #\u5730\u5740
    host: localhost
    #\u7AEF\u53E3
    port: 6379
    #\u7D22\u5F15\u5E93
    database: 1
    #\u5BC6\u7801
    password:
    #\u8D85\u65F6\u65F6\u95F4
    timeout: 5000ms
  cache:
    #\u8BBE\u7F6E\u7F13\u5B58\u7C7B\u578B
    type: redis
    redis:
      #\u7F13\u5B58\u5B58\u6D3B\u65F6\u95F4\uFF0C\u4E0D\u8BBE\u7F6E\u5219\u6CA1\u6709\u8FC7\u671F\u65F6\u95F4
      time-to-live: 1800000ms

logging:
  level:
    root: error